#!/usr/bin/env python3

import os
import sys
from dotenv import load_dotenv
import openai
from openai import OpenAI

load_dotenv("/PATH_TO_.env_FILE/.env")
PATH_TO_DOCUMENTS = os.environ.get('PATH_TO_DOCUMENTS')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')

client = OpenAI()

# Upload File
for file in os.listdir(PATH_TO_DOCUMENTS):
    if file.endswith(".pdf"):
        pdf_path = PATH_TO_DOCUMENTS + file

file = client.files.create(
  file=open(pdf_path, "rb"),
  purpose='assistants'
)

# Create Assistant
assistant = client.beta.assistants.create(
    name="VitalPBX Technical Support",
    instructions="You are a commercial and support expert at VitalPBX LLC. You analyze data present in .pdf files, understand the content, and come up with answer related to the PDF files.",
    tools=[{"type": "code_interpreter"}, {"type": "retrieval"}],
    model="gpt-4-1106-preview",
    file_ids=[file.id]
)

# Get Assistant ID
assistant_id = assistant.id

print(assistant_id)
